[package]
name = "pace"
version = "0.0.0"
edition = "2021"
authors = ["Sebastian Köln <s3bk@protonmail.com>"]
description = "Progress Reporting"
repository = "https://github.com/s3bk/pace"
homepage = "https://github.com/s3bk/pace"
license = "MIT"
keywords = ["progress", "report"]
